language: python
python:  3.7
install:
    - pip install -r requirements.txt
    - pip install pyinstaller tornado
script:
    - python setup.py bdist_wheel
    - pyinstaller novowrap/ui.py -n novowrap
    - pyinstaller novowrap/ui.py -n novowrap -w -y
    - dist/novowrap/novowrap -help
