language: python
python:  3.7
install:
    - pip install -r requirements.txt
    - pip install pyinstaller tornado
      pip install --upgrade setuptools
    - python setup.py bdist_wheel
    - pip install dist/*.whl
    - python -m novowrap --help
script:
    - pyinstaller novowrap/ui.py -n novowrap
    - pyinstaller novowrap/ui.py -n novowrap -w -y
