matrix:
    include:
        - name: "Python 3.7 on Linux"
          os: linux
          language: python
          python: 3.7
        - name: "Python 3.7 on macOS"
          os: osx
          language: shell
          osx_image: xcode11
          python: 3.7
        - name: "Python 3.7 on Windows"
          os: windows
          language: shell
          before_install:
              - choco install python
install:
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - pip install pyinstaller tornado
    - python setup.py bdist_wheel
    - pip install dist/*.whl
script:
    - python -m novowrap --help
    - pyinstaller novowrap/ui.py -n novowrap
    - pyinstaller novowrap/ui.py -n novowrap -w -y
