language: python
python:  3.7
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install pyinstaller tornado --use-mirrors
script:
    - python setup.py bdist_wheel
    - pyinstaller novowrap/ui.py -n novowrap
    - pyinstaller novowrap/ui.py -n novowrap -w
    - dist/novowrap/novowrap -help
