matrix:
    include:
        - name: "Python 3.7 on Linux"
          os: linux
          language: python
          python: 3.8
          after_install:
              - python3 setup.py bdist_wheel
              - pip3 install dist/*.whl
          script:
              - python3 -m novowrap --help
        - name: "Python 3.7 on macOS"
          os: osx
          language: shell
          osx_image: xcode11
          python: 3.8
          after_install:
              - python3 setup.py bdist_wheel
              - pip3 install dist/*.whl
          script:
              - python3 -m novowrap --help
        - name: "Python 3.7 on Windows"
          os: windows
          language: shell
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
          before_install:
              - choco install python
              - python -m pip install --upgrade pip
          after_install: 
              - python setup.py bdist_wheel
              - pip3 install dist/*.whl
          script:
              - python -m novowrap --help
install:
    - pip3 install --upgrade setuptools
    - pip3 install -r requirements.txt
    - pip3 install pyinstaller tornado
script:
    - pyinstaller novowrap/ui.py -n novowrap
    - pyinstaller novowrap/ui.py -n novowrap -w -y
deploy:
    - provider: releases
      api_key: $RELEASE_TOKEN
      local_dir: dist/novowrap
      skip_cleanup: true
      draft: true
      on:
          tags: true
      name: $TRAVIS_TAG

